spring:
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_ADDR:ENC(h9xRlu7jZ2/v7Ijedz96Wx7ISYvkYasXTlIVeKfKNJyXLKW3oc10vzNcLQ3IroscJpC4AbUwOSulW3Rwt52+ytaSnnw6Vs6FWDjNR8S72UZzLJqBPxZ7ryTG2ZHJoqYou5yW7/+McVaZRLatY54LEgG23rU6rW1x)}
    username: ${MYSQL_USERNAME:ENC(O0WJdHK10k6bhTSQJbTEGrsBytLKSmRX)}
    password: ${MYSQL_PASSWORD:ENC(xk8u9sk/O8iQp5hULhWtASCPvSC6R5o+AggfXiITFKR7iA8kGncdzw==)}
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
  redis:
    host: ${REDIS_ADDR:ENC(TPLVJLDQklIWi8bUBfuK9NlhEsr0pUKN)} # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: ${REDIS_PORT:ENC(FHhKVruYE8+nWbYJS4B07Q==)} # Redis服务器连接端口
    password: ${REDIS_PWD:ENC(fMELtMSEcwBw2h37zL58HwThVlByZ9j0IVBE+0b9zGE=)} # Redis服务器连接密码（默认为空）
    timeout: 3000ms # 连接超时时间（毫秒）
  application:
    name: file-model-service${UNIQUE_ID:0}
  cloud:
    nacos:
      server-addr: ENC(VdzZDIUI6EP3mXnpOmb0l46RpSA5HlJgqy9/ZxU0Mx3U777m+o9J6Q==)
      username: ENC(qqqHXA1bwhhYPJ9SXXZqyO5j//wygYDK)
      password: ENC(v1J0g/bB0xWCi9Te8mwH1o309G9xtm6q1L8SeCkYdYY=)
      config:
        file-extension: yaml
      discovery:
        ip: ${SERVER_ADDR:ENC(Y5HcvI+7TfzJVRmAMpYDqR0bwJqzwMzdpQ8RCIr1y2w=)}
  rabbitmq:
    host: ${MQ_ADDR:ENC(EdvVJoPyMDMWlcxJ/dKnRnP6hIH/eyyLo0pHab0HbWE=)} # rabbitMQ的ip地址
    port: ${MQ_PORT:ENC(lA59hkbOPGfPYnd/ossrjwfdj1g+QKzy)} # 端口
    username: ${MQ_USERNAME:ENC(h4sx/sPEXk8MsDhsWNc1pwGRrxucMNqz)}
    password: ${MQ_PWD:ENC(pnc0ZWw3h49DWEJtygRU79rEw3ZBsvl0NYRTW9CuIPKQDydSRTHRYw==)}
    virtual-host: /
    publisher-confirm-type: simple
    publisher-returns: true
    listener:
      simple:
        prefetch: ${MQ_PREFETCH:5}
        concurrency: ${MIN_CONCURRENCY:5}
        max-concurrency: ${MAX_CONCURRENCY:10}
        acknowledge-mode: manual
    exchange-type: ${EXCHANGE_TYPE:ENC(WUANSPJwXgpu928eZLdjtHxqz08RemFd)}
    pre-command: ${PRE_COMMAND:ENC(nRHKgZnkufKa8nZmJ6MsMjF26vxXrT7mRxmRgSqW6Gs=)}
management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 9100
page:
  size: ${DEFAULT_SIZE:ENC(247Kmy9z8U5mzJ2r/ZBKAuHF3/cxGaGW)}

file:
  logger:
    handler: ${Logger:slf4j}
    enable: true
  image-file-size: ${IMAGE_FILE_SIZE:ENC(iJ4SBFg1JS8G0zMQ0ysSzpjOTUivPgZa)}
