spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_ADDR:ENC(xMRgIMkkMeGcEa2r7Evzw4AZMCHiDpIGN7ETNEIallJTWSl30aRIZqniNoQpgsujTuur8qAezCXaaNxOYKLvlFQjS7pPoe3oBCz2fFUMRhZ0G2qZG8ZYUnUjnkIZyUWDSbns7no1+8L02z0CP+ghKbPao+l7DolA9lLGx2vUbZY=)}
    username: ${MYSQL_USERNAME:ENC(O0WJdHK10k6bhTSQJbTEGrsBytLKSmRX)}
    password: ${MYSQL_PASSWORD:ENC(xk8u9sk/O8iQp5hULhWtASCPvSC6R5o+AggfXiITFKR7iA8kGncdzw==)}
  redis:
    host: ${REDIS_ADDR:ENC(7+i1abkV1AAW737zy56ZvAWdcUq8AKM0WufHtc+3eqo=)} # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: ${REDIS_PORT:ENC(vZrw6ItoyBBaKAHqyYi6zzoVUc8BRiM+)} # Redis服务器连接端口
    password: ${REDIS_PWD:ENC(BWt70dzHaoTtVWtJWZF2c592HJgBHV9CdjwRTcOos/qort27DDnJag==)} # Redis服务器连接密码（默认为空）
    timeout: 3000ms # 连接超时时间（毫秒）
  application:
    name: rvc-communication-service

  cloud:
    nacos:
      server-addr: ${NACOS_SERVER_ADDR:ENC(VdzZDIUI6EP3mXnpOmb0l46RpSA5HlJgqy9/ZxU0Mx3U777m+o9J6Q==)}
      username: ${NACOS_SERVER_USER:ENC(qqqHXA1bwhhYPJ9SXXZqyO5j//wygYDK)}
      password: ${NACOS_SERVER_PASSWORD:ENC(v1J0g/bB0xWCi9Te8mwH1o309G9xtm6q1L8SeCkYdYY=)}
      config:
        file-extension: yaml
        namespace: 98732302-bf12-40a5-8d93-7f2d97187a12
      discovery:
        namespace: 98732302-bf12-40a5-8d93-7f2d97187a12
        cluster-name: BJ
        ip: ${SERVER_ADDR:ENC(Im0338XUjGgPi8/noOyN48Ine8N+5IQptwjuGJRD1Lk=)}
  rabbitmq:
    host: 1.94.28.8
#    ${MQ_ADDR:ENC(oJOoWcwxDz1yPbEsfKYhXNSBiyh6hKYrkeBAt6bXWNU=)} # rabbitMQ的ip地址
    port: ${MQ_PORT:ENC(7A9EOZIGloPHE+ofbF3eGne7n+NKqghG)} # 端口
    username: ${MQ_USERNAME:ENC(msEZZscluZTBTTAyc7ECn1cKzvzSX5fA)}
    password: ${MQ_PWD:ENC(YbfbsvqhMk5HzoBoXsjKOwzKLEJW64uEtn2Lwcuzdfdb6l2H9+V6og==)}
    virtual-host: /
    publisher-confirm-type: simple
    publisher-returns: true
    listener:
      simple:
        prefetch: ${MQ_PREFETCH:5}
        concurrency: ${MIN_CONCURRENCY:5}
        max-concurrency: ${MAX_CONCURRENCY:10}
        acknowledge-mode: manual
management:
  endpoints:
    web:
      exposure:
        include: '*'
  server:
    port: 9201

assistant:
  service:
    id:
      snowflake:
        register: register-redis
        startTime: 2023-12-05 00:00:00
