server:
  port: 9200

spring:
  datasource:
    url: jdbc:mysql://1.94.28.8:3306/rvc?characterEncoding=utf8&useSSL=false
    username: "root"
    password: "genius_server_0704"
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB
#  redis:
    #    password: 123456
#    port: 6379
    #    host: 192.168.31.26

    database: 4
    timeout: 2000
