spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/rvc2?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: root
  redis:
    host: localhost # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: Genius123 # Redis服务器连接密码（默认为空）
    timeout: 3000ms # 连接超时时间（毫秒）
  application:
    name: rvc-feedback-service
  cloud:
    nacos:
      server-addr: ENC(VdzZDIUI6EP3mXnpOmb0l46RpSA5HlJgqy9/ZxU0Mx3U777m+o9J6Q==)
      username: ENC(qqqHXA1bwhhYPJ9SXXZqyO5j//wygYDK)
      password: ENC(v1J0g/bB0xWCi9Te8mwH1o309G9xtm6q1L8SeCkYdYY=)
      discovery:
        namespace: 98732302-bf12-40a5-8d93-7f2d97187a12
      config:
        file-extension: yaml
#        namespace: 41325882-1160-44b1-a0b8-7d2ebb683d0e
        namespace: 98732302-bf12-40a5-8d93-7f2d97187a12
        shared-configs:
          - dataId: feign-config.yaml
            refresh: true
            group: DEFAULT_GROUP
management:
  endpoints:
    web:
      exposure:
        include: '*'
  server:
    port: 9401

assistant:
  service:
    id:
      snowflake:
        workerId: 1
        dataCenterId: 1
        startTime: 2023-12-05 00:00:00


feign:
  client:
    config:
      default:
        connect-timeout: 30000
        read-timeout: 30000

  httpclient:
    enabled: true # 支持HttpClient的开关
    max-connections: 200 # 最大连接数
    max-connections-per-route: 50 # 单个路径的最大连接数
  sentinel:
    enabled: true
