server:
  port: ${SERVER_PORT:9400}

spring:
  config:
    import: classpath:you-cant-see-that.yml
  profiles:
    active: ${ACTIVE:dev}


assistant:
  mysql:
    query-group:
      feedback_list: fb_id,uid,title,type,status,comment_num,up_num,create_at
      feedback_detail: fb_id,uid,title,content,type,status,comment_num,up_num,create_at
      feedback_comment: cm_id,reply_fb_id,reply_cm_id,uid,comment,like_num,create_at


rvc:
  feedback:
    feedback_order_column: create_at,up_num,comment_num
    comment_order_column: create_at,like_num
