server:
  port: ${SERVER_PORT:9300}

spring:
  config:
    import: classpath:you-cant-see-that.yml
  profiles:
    active: ${ACTIVE:test}


rvc:
  query-group:
    home_notice: notice_id,title,author,cover,watch_num,create_at
    detail_notice: notice_id,title,author,cover,watch_num,create_at,content,like_num
  limit:
    notice:
      home: 6
      web: 10

